# hoarder

services:
  hoarder:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    container_name: hoarder
    networks:
      - pvnet
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MEILI_ADDR=http://meilisearch:7700
      - BROWSER_WEB_URL=http://hoarder-chrome:9222
      #- OPENAI_API_KEY=${OPENAI_API_KEY}
      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      - DATA_DIR=/data # DON'T CHANGE THIS
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - /mnt/nebula/docker/appdata/hoarder:/data
    ports:
      - 3020:3000
    env_file:
      - /env-files/common.env
      - /env-files/hoarder.env
 
  hoarder-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: hoarder-chrome
    networks:
      - pvnet
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    env_file:
      - /env-files/common.env
      - /env-files/hoarder.env
      
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    container_name: meilisearch
    networks:
      - pvnet
    restart: unless-stopped
    env_file:
      - /env-files/common.env
      - /env-files/hoarder.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MEILI_NO_ANALYTICS=true
    volumes:
      - /mnt/nebula/docker/appdata/meilisearch:/meili_data

networks:
   pvnet:
     external: true