# Overseerr

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    networks:
      - pvnet  
    environment:
      #- LOG_LEVEL=debug
      - TZ=${TZ}
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ${DOCKER_APP_BASE_PATH}/overseerr:/app/config
    labels:
      - com.centurylinklabs.watchtower.enable=true      

networks:
   pvnet:
     external: true   