version: '3.6'

services:
  mainsail:
    image: ghcr.io/mainsail-crew/mainsail
    container_name: mainsail
    ports:
      - 8819:80
    volumes:
      - /srv/docker/apps/mainsail/config.json:/usr/share/nginx/html/config.josn
    restart: unless-stopped
