version: '3.2'

services:
  mainsail:
    image: ghcr.io/mainsail-crew/mainsail 
    ports:
      - "8001:80"
    volumes:
      - '/srv/docker/apps/mailsail/config.json:/usr/share/nginx/html/config.josn"
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
        - node.hostname == docker03
