version: '3.9'

services:
  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest
    container_name: adguardhome-sync
    environment:
      - PUID=1980
      - PGID=1980
      - TZ=America/Chicago
      - CONFIGFILE=/config/adguardhome-sync.yaml #optional
    volumes:
      - /srv/docker/appdata/adguardhome-sync/config:/config
    ports:
      - 8030:8080
    restart: unless-stopped
