version: '3.6'

services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    ports:
      - "8080:8080"
    environment:
      TZ: 'America/Chicago'
    restart: unless-stopped
    volumes:
      - /srv/docker/appdata/sabnzbd:/config
      - /mnt/galaxy/media/downloads/complete:/downloads
      - /mnt/galaxy/media/downloads/incomplete:/incomplete-downloads
      #- /srv/docker/appdata/teleport/data:/shared
    deploy:
     replicas: 1
     placement:
       constraints: [node.hostname == ra]
