version: "3.6"

services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1980
      - PGID=1980
      - TZ=America/Chicago
      - CHROME_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - /srv/docker/appdata/chromium:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
