version: '3.6'

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1980
      - PGID=1980
      - TZ=America/Chicago
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.peav.us #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /srv/docker/appdata/code-server:/config
    ports:
      - 8444:8443
#    restart: unless-stopped
#    deploy:
#      replicas: 1
#      placement:
#        constraints: [node.labels.nodetype == data]
