version: '3.6'

services:
  crashplan-pro:
    image: jlesage/crashplan-pro
    container_name: crashplan-pro
    hostname: crashplan-pro
    ports:
      - 5800:5800
    environment:
      - TZ=America/Chicago
      #- PUID=1980
      #- PGID=1980
      - CRASHPLAN_SRV_MAX_MEM=8192M
    volumes:
      - /srv/docker/appdata/crashplan-pro:/config
      #- /nebula/docker/appdata/crashplan-pro:/config
      #- /galaxy:/storage/galaxy
      #- /nebula:/storage/nebula
      - /mnt/galaxy:/storage/galaxy
