version: '3.6'

services:
  crashplan-pro:
    image: jlesage/crashplan-pro
    ports:
      - 5800:5800
    environment:
      - TZ=America/Chicago
      - PUID=0
      - PGID=0
      - CRASHPLAN_SRV_MAX_MEM=8192M
    volumes:
      - /srv/docker/appdata/crashplan-pro:/config
      - /galaxy:/storage/galaxy
      - /nebula:/storage/nebula
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.nodetype == data]
