version: '3.6'

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    environment:
      - PUID=1980
      - PGID=1980
      - TZ=America/Chicago
    ports:
      - 8084:80
    volumes:
      - /mnt:/srv/mnt
      #- /mnt/nebula/docker:/srv/mnt/nebula/docker
      - /mnt/galaxy/media:/srv/mnt/galaxy/media
      - /srv/docker:/srv/local/docker
      #- /nebu:/srv/nebula
      - /srv/docker/appdata/filebrowser/database.db:/database.db
      - /srv/docker/appdata/filebrowser/.filebrowser.json:/.filebrowser.json
    labels:
      - com.centurylinklabs.watchtower.enable=true
