version: '3'

services:
  guacamole:
    container_name: guacamole
    image: jwetzell/guacamole
    restart: unless-stopped
    ports:
      - 8086:8080
    volumes:
      - /srv/docker/appdata/guacamole:/config
  
  
  
  
  
#  guacd:
#    container_name: guacd
#    image: guacamole/guacd:latest
#    restart: unless-stopped
#  guacamole:
#    container_name: guacamole
#    image: guacamole/guacamole:latest
#    restart: unless-stopped
#    ports:
#      - 8086:8080
#    environment:
#      GUACD_HOSTNAME: "guacd"
#      MYSQL_HOSTNAME: ${GUACDB_HOSTNAME}
#      MYSQL_DATABASE: ${GUACDB_DATABASE}
#      MYSQL_USER: ${GUACDB_USERNAME}
#      MYSQL_PASSWORD: ${GUACDB_PASSWORD}
#      TOTP_ENABLED: "true"
