version: '3.2'

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - PUID=1000
      - PGID=998
      - TZ=America/Chicago
    volumes:
      - /srv/docker/appdata/heimdall:/config
    ports:
      - 8001:80
      - 4431:443
    restart: unless-stopped
