version: '3.6'

services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    user: root
    volumes:
      - /srv/docker/appdata/homer:/www/assets
    ports:
      - 8081:8080
    environment:
      - INIT_ASSETS=1 # default
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == ra]
