version: '3.6'

services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    #user: root
    volumes:
      - /nebula/docker/appdata/homer:/www/assets
    ports:
      - 8081:8080
    environment:
      - INIT_ASSETS=1 # default
      - TZ=America/Chicago
      - PUID=0
      - GUID=0
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints: [node.label.nodetype == tiny]
