version: "3.6"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      -DOCKER_INFLUXDB_INIT_MODE=setup
      -DOCKER_INFLUXDB_INIT_USERNAME=$username
      -DOCKER_INFLUXDB_INIT_PASSWORD=$password
      -DOCKER_INFLUXDB_INIT_ORG=pv
      -DOCKER_INFLUXDB_INIT_BUCKET=pv-bucket
    volumes:
      - /srv/docker/appdata/influxdb:/var/lib/influxdb2
      - /srv/docker/appdata/influxdb:/etc/influxdb2
    ports:
      - 8086:8086
    restart: unless-stopped
