version: "3.6"

services:
  influxdb2:
    image: influxdb:latest
    container_name: influxdb2
    env_file: /srv/docker/env/.env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=pv
      - DOCKER_INFLUXDB_INIT_BUCKET=pv-bucket
    volumes:
      - ${APPDATA_PATH}/influxdb2/data:/var/lib/influxdb2
      - ${APPDATA_PATH}/influxdb2/config:/etc/influxdb2
    ports:
      - 8086:8086
    restart: unless-stopped
