version: '3.6'

services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    ports:
      - 9925:80
    environment:
      - TZ=America/Chicago
      - PUID=0
      - PGID=0
      #  Default Recipe Settings
      - RECIPE_PUBLIC=true
      - RECIPE_SHOW_NUTRITION=true
      - RECIPE_SHOW_ASSETS=true
      - RECIPE_LANDSCAPE_VIEW=true
      - RECIPE_DISABLE_COMMENTS=false
      - RECIPE_DISABLE_AMOUNT=false

      # Gunicorn
      # WEB_CONCURRENCY: 2
      # WORKERS_PER_CORE: 0.5
      # MAX_WORKERS: 8
    volumes:
      - /nebula/docker/appdata/mealie:/app/data
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.nodetype == data]
