version: '3.6'

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    ports:
      - 4443:443
    environment:
      - PUID=1980
      - PGID=1980
      - TZ=America/Chicago
    volumes:
      - /srv/docker/appdata/nextcloud:/config
      - /mnt:/data
    restart: unless-stopped