
version: '3.6'

services:
  npm:
    image: b4bz/homer
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    volumes:
      - /srv/docker/appdata/npm:/data
      - /galaxy/certificates/letsencrypt:/etc/letsencrypt
    deploy:
      replicas: 1
