version: '3.6'

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    volumes:
      #- /nebula/docker/appdata/npm:/data
      #- /nebula/docker/share/certificates/npm/:/etc/letsencrypt
      - /srv/docker/appdata/npm:/data
      - /srv/docker/share/certificates/npm/:/etc/letsencrypt
    environment:
      - DB_SQLITE_FILE=/data/npm.sqlite
      - TZ=America/Chicago
      - PUID=0
      - GUID=0
    deploy:
     replicas: 1
     placement:
        constraints: [node.labels.nodetype == tiny]
