version: '3.6'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - TZ=America/Chicago
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /srv/docker/appdata/plextest:/config
      - /mnt/galaxy/media/tv:/tv
      - /mnt/galaxy/media/movies:/movies
    ports:
      -32400:32400
      -1900:1900/udp
      -3005:3005
      -5353:5353/udp
      -8324:8324
      -32410:32410/udp
      -32412:32412/udp
      -32413:32413/udp
      -32414:32414/udp
      -32469:32469
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
    restart: unless-stopped
    deploy:
     replicas: 1
     placement:
       constraints: [node.hostname == osiris]
