version: '3.6'

services:
  qdirstat:
    image: jlesage/qdirstat
    ports:
      - 5805:5800
    volumes:
      - /srv/docker/appdata/qdirstat:/config
      - /galaxy:/storage/galaxy:ro
      - /nebula:/storage/nebula:ro
      - /:/storage:ro
    restart: unless-stopped
