version: "3.2"

services:
  stable-diffusion-webui:
    image: universonic/stable-diffusion-webui:minimal
    command: --no-half --no-half-vae --precision full --api 
    runtime: nvidia
    restart: unless-stopped
    ports:
      - "7860:8080/tcp"
    volumes:
      - /srv/docker/appdata/stable-diffusion-webui/inputs:/app/stable-diffusion-webui/inputs
      - /srv/docker/appdata/stable-diffusion-webui/textual_inversion_templates:/app/stable-diffusion-webui/textual_inversion_templates
      - /srv/docker/appdata/stable-diffusion-webui/embeddings:/app/stable-diffusion-webui/embeddings
      - /srv/docker/appdata/stable-diffusion-webui/extensions:/app/stable-diffusion-webui/extensions
      - /srv/docker/appdata/stable-diffusion-webui/models:/app/stable-diffusion-webui/models
      - /srv/docker/appdata/stable-diffusion-webui/localizations:/app/stable-diffusion-webui/localizations
      - /srv/docker/appdata/stable-diffusion-webui/outputs:/app/stable-diffusion-webui/outputs
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.iface != extern"
      restart_policy:
        condition: unless-stopped
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
