version: '3.6'

services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /nebula/docker/appdata/tautulli:/config
      - /nebula/docker/appdata/tautulli/logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.nodetype == tiny]
