version: '3.6'

services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1980
      - PGID=1980
      - TZ=America/Chicago
    volumes:
      - /nebula/docker/appdata/tautulli:/config
      - /nebula/docker/appdata/tautulli/logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
