version: '3.6'

services:
  teleport:
    # gravitational/teleport · Quay
    # https://quay.io/repository/gravitational/teleport?tab=tags&tag=latest
    # image: quay.io/gravitational/teleport
    image: public.ecr.aws/gravitational/teleport:10
    ports:
      - "3022:3022"
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "3026:3026"
      - "3027:3027"
      - "3028:3028"
      - "3036:3036"
      - "3080:3080"
    restart: unless-stopped
    volumes:
      - /srv/docker/appdata/teleport/config:/etc/teleport
      - /srv/docker/appdata/teleport/data:/var/lib/teleport
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == ra]
