version: '3.6'

services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    restart: unless-stopped
    ports:
      - 8888:8888
    environment:
      - PUID=1980
      - PGID=1980
      - TZ=America/Chicago
    volumes:
      - /srv/docker/appdata/unmanic:/config
      - /mnt/galaxy/media:/library
      - /mnt/galaxy/downloads/unmanic:/tmp/unmanic
