
version: '3.6'

services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    ports:
      - 3001:3001
    environment:
      - TZ=America/Chicago
      - PUID=0
      - PGID=0
    volumes:
      - /srv/docker/appdata/uptime-kuma:/app/data
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == ra]
