version: '3.6'

services:
  sabnzbd:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - TZ=America/Chicago
      - WATCHTOWER_CLEANUP=true 
      - WATCHTOWER_LABEL_ENABLE=true 
      - WATCHTOWER_SCHEDULE='0 7 * * *'
    restart: unless-stopped
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
