version: '3.6'

services:
  zwavejs2mqtt:
    image: zwavejs/zwavejs2mqtt:latest
    container_name: zwavejs2mqtt
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    ports:
      - 8091:8091
      - 3000:3000
    environment:
      - TZ=America/Chicago
      - PUID=1980
      - PGID=1980
      - SESSION_SECRET=${SESSION__SECRET}
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_e695839510a4eb118b5e2a259da30875-if00-port0:/dev/zwave
    volumes:
      - /srv/docker/appdata/zwavejs2mqtt:/usr/src/app/store

