version: '3.6'

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Chicago
    restart: unless-stopped
    volumes:
      - /srv/docker/appdata/sabnzbd:/config
      - /mnt/galaxy/media/downloads:/downloads
      - /mnt/galaxy/media/downloads/incomplete:/incomplete-downloads

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - TZ=America/Chicago
    restart: unless-stopped
    volumes:
      - /srv/docker/appdata/radarr:/config
      - /mnt/galaxy/media/movies:/movies
      - /mnt/galaxy/media/downloads:/downloads
     
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - TZ=America/Chicago
    restart: unless-stopped
    volumes:
      - /srv/docker/appdata/sonarr:/config
      - /mnt/galaxy/media/tv:/tv
      - /mnt/galaxy/media/downloads:/downloads

  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    ports:
      - "5076:5076"
    environment:
      - TZ=America/Chicago
    restart: unless-stopped
    volumes:
      - /srv/docker/appdata/nzbhydra2:/config
      - /mnt/galaxy/media/downloads:/downloads

networks:
  default:
    name: test
    external: true
