# tautulli

services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APP_BASE_PATH}/tautulli:/config
      - ${DOCKER_APP_BASE_PATH}/tautulli/logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
