# Scanopy

services:
  scanopy-db:
    container_name: scanopy-db
    image: postgres:17-alpine
    hostname: scanopy-db
    restart: unless-stopped
    networks:
      - pvnet
    env_file: 
      - /env-files/scanopy.env
    # environment:
      # POSTGRES_DB: ${SCANOPY_DB_NAME}
      # POSTGRES_USER: ${SCANOPY_DB_USER}
      # POSTGRES_PASSWORD: ${SCANOPY_DB_PASSWORD}
    volumes:
      - ${DOCKER_APP_BASE_PATH}/scanopy/db:/var/lib/postgresql/data

  scanopy-server:
    container_name: scanopy-server
    image: ghcr.io/scanopy/scanopy/server:latest
    hostname: scanopy-server
    restart: unless-stopped
    networks:
      - pvnet
    depends_on:
      - scanopy-db
    env_file: 
      - /env-files/scanopy.env
    environment:
      - SCANOPY_UI_ENABLED=true
      #- SCANOPY_DATABASE_URL=postgres://${SCANOPY_DB_USER}:${SCANOPY_DB_PASSWORD}@scanopy-db:5432/${SCANOPY_DB_NAME}
      - SCANOPY_PUBLIC_URL=http://${HOST_IP:-127.0.0.1}:60072
      - SCANOPY_LOG_LEVEL=debug  # Set to debug to see WHY it's disabling the UI
      - TZ=${TZ}
      - HOST=0.0.0.0
      - SCANOPY_RESET_CONFIG_ON_START=true
    ports:
      - "60072:60072"
    volumes:
      - ${DOCKER_APP_BASE_PATH}/scanopy/config:/app/config

  scanopy-daemon:
    container_name: scanopy-daemon
    image: ghcr.io/scanopy/scanopy/daemon:latest
    hostname: scanopy-daemon
    restart: unless-stopped
    # Essential for ARP scanning your Albertville network
    network_mode: host
    privileged: true
    env_file: 
      - /env-files/scanopy.env
    environment:
      - SCANOPY_SERVER_URL=http://127.0.0.1:60072
      - SCANOPY_LOG_LEVEL=info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  pvnet:
    external: true
