# FileBrowser

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    env_file: 
      - /env-files/common.env  
    environment:
      #- PUID=$(id -u)
      #- PGID=$(id -g)
      - TZ=${TZ}
    volumes:
      - /mnt:/srv #Change to match your directory
      - ${DOCKER_APP_BASE_PATH}/filebrowser/filebrowser.db:/database/filebrowser.db
      - ${DOCKER_APP_BASE_PATH}/filebrowser/settings.json:/config/settings.json
    ports:
      - 8084:80 #Change the port if needed
    labels:
      - com.centurylinklabs.watchtower.enable=true
