# guacamole

services:
  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    restart: unless-stopped
    user: "3001:3001"
    env_file: 
      - /env-files/guacamole.env 
    #group_add:
    #  - 3001
    networks:
      - pvnet
    ports:
      - 8086:8080/tcp
    # depends_on:
    #- guacd
    environment:
      GUACD_HOSTNAME=guacd
      MYSQL_DATABASE=${MYSQL_DATABASE}
      MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      MYSQL_PASSWORD=${MYSQL_PASSWORD}
      MYSQL_USERNAME=${MYSQL_USERNAME}
      LOG_LEVEL=debug
    volumes:
      # - ${DOCKER_APP_BASE_PATH}/guacamole:/config
      - /mnt/nebula/docker/appdata/guacamole:/config
    labels:
      - com.centurylinklabs.watchtower.enable=true

  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    env_file: 
      - /env-files/guacamole.env
    user: "3001:3001"
    # group_add:
    #   - 3001
    networks:
      - pvnet
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
   pvnet:
     external: true
