# ai

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - OLLAMA_KEEP_ALIVE=24h
      - ENABLE_IMAGE_GENERATION=True
      #- COMFYUI_BASE_URL=http://stable-diffusion-webui:7860
    networks:
      - ai-stack
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/docker/ollama:/root/.ollama
    ports:
      - "11434:11434" # Add this line to expose the port
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    networks:
      - ai-stack
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      #- ENABLE_RAG_WEB_SEARCH=True
      #- RAG_WEB_SEARCH_ENGINE=searxng
      #- RAG_WEB_SEARCH_RESULT_COUNT=3
      #- RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      #- SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/docker/open-webui:/app/backend/data
    depends_on:
      - ollama
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8080:8080" # Add this line to expose the port
    labels:
      - com.centurylinklabs.watchtower.enable=true

  stable-diffusion-automatic1111-download:
    image: stable-diffusion-download:latest
    container_name: stable-diffusion-automatic1111-download
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/docker/stable-diffusion-automatic1111/data:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true

  stable-diffusion-comfy-download:
    image: stable-diffusion-download:latest
    container_name: stable-diffusion-comfy-download
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/docker/stable-diffusion-comfy/data:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true    

  stable-diffusion-automatic1111:
    image: stable-diffusion-automatic1111:latest
    container_name: stable-diffusion-automatic1111
    restart: unless-stopped
    networks:
      - ai-stack
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/docker/stable-diffusion-automatic1111/data:/data
      - /srv/docker/stable-diffusion-automatic1111/output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]
    ports:
      - "7860:7860" # Add this line to expose the port
    labels:
      - com.centurylinklabs.watchtower.enable=true      

  stable-diffusion-comfy:
    image: stable-diffusion-comfy:latest
    container_name: stable-diffusion-comfy
    restart: unless-stopped
    networks:
      - ai-stack
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/docker/stable-diffusion-comfy/data:/data
      - /srv/docker/stable-diffusion-comfy/output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]
    ports:
      - "7861:7860" # Add this line to expose the port
    labels:
      - com.centurylinklabs.watchtower.enable=true          

networks:
  ai-stack:
    external: true