version: '3.6'

services:
  crashplan-pro:
    image: jlesage/crashplan-pro:latest
    container_name: crashplan-pro
    ports:
      - 5800:5800
    environment:
      - TZ=${TZ}
      - PUID=3001
      - GUID=3001
      #- PUID=${PUID}
      #- GUID=${PGID}
      - CRASHPLAN_SRV_MAX_MEM=8192M
    volumes:
      - ${DOCKER_APP_BASE_PATH}/crashplan-pro:/config
      - /mnt/galaxy:/storage/galaxy
      - /mnt/nebula:/storage/nebula
    labels:
      - "com.centurylinklabs.watchtower.enable=true"   
