# OrcaSlicer

services:
  orcaslicer:
    image: lscr.io/linuxserver/orcaslicer:latest
    container_name: orcaslicer
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APP_BASE_PATH}/orcaslicer/config:/config
      - ${DOCKER_APP_BASE_PATH}/orcaslicer/data:/data
    ports:
      - 3010:3000
      - 3011:3001
    shm_size: "4gb"
    labels:
      - com.centurylinklabs.watchtower.enable=true