# Magicmirror

services:
  magicmirror:
    image: karsten13/magicmirror:latest
    container_name: maggicmirror
    restart: unless-stopped
    networks:
      - pvnet     
    environment:
    #  - PUID=${PUID}
    #  - PGID=${PGID}
    #  - TZ=${TZ}
      - M_SCENARIO="server"
      - MM_UID=${PUID}
      - MM_GID=${PGID}
    volumes:
      - ${DOCKER_APP_BASE_PATH}/magicmirror/config:/opt/magic_mirror/config
      - ${DOCKER_APP_BASE_PATH}/magicmirror/modules:/opt/magic_mirror/modules
      - ${DOCKER_APP_BASE_PATH}/magicmirror/css://opt/magic_mirror/css
    ports:      
      - 8082:8080
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
   pvnet:
     external: true  