version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command:
      - --cleanup=true
    restart: always
    ports:
      - "8089:8080"    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
