services:
  immich-server:
    container_name: immich_server
    hostname: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: unless-stopped
    healthcheck:
      disable: false
    env_file:
      #- ${DOCKER_BASE_PATH}/env-files/immich.env 
      #- /env-files/immich.env
      - /mnt/nebula/docker/env-files/immich.env 
    networks:
      - pvnet
    #network_mode: "container:gluetun"
    # removed to use gluetun
    ports:
      - 2283:2283
    environment:
      - DB_HOSTNAME=immich-postgres
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - REDIS_HOSTNAME=immich-redis
    volumes:
      - ${DOCKER_APP_BASE_PATH}/immich/data:/data
      # Managed Storage: New phone backups go here
      - ${NAS_GALAXY_BASE_PATH}/media/photos/immich_library:/usr/src/app/upload
      # External Storage: Your existing bulk photos (Mapped as Read-Only)
      - ${NAS_GALAXY_BASE_PATH}/media/photos:/mnt/media/photos:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    
  immich-machine-learning:
    container_name: immich_machine_learning
    hostname: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    restart: unless-stopped
    env_file:
      #- ${DOCKER_BASE_PATH}/env-files/immich.env 
      - /env-files/immich.env
    networks:
      - pvnet
    volumes:
      # SSD: Fast model loading
      - ${DOCKER_APP_BASE_PATH}/immich/model-cache:/cache

  database:
    container_name: immich_postgres
    hostname: immich-postgres
    image: ghcr.io/immich-app/postgres:16-vectorchord0.5.3-pgvector0.8.1
    # REMOVED THE STRAY "app/postgres" LINE HERE
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      #- ${DOCKER_BASE_PATH}/env-files/immich.env 
      - /env-files/immich.env
    networks:
      - pvnet
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      # SSD: Fast database queries and timeline scrolling
      - ${DOCKER_APP_BASE_PATH}/immich/postgres:/var/lib/postgresql/data
    shm_size: 256mb
 
  redis:
    container_name: immich_redis
    hostname: immich-redis
    image: docker.io/valkey/valkey:9-alpine
    restart: unless-stopped
    env_file:
      #- ${DOCKER_BASE_PATH}/env-files/immich.env 
      - /env-files/immich.env
    networks:
      - pvnet
    healthcheck:
      # Alpine uses a lightweight shell, so CMD-SHELL is the safest way to call redis-cli
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
   pvnet:
     external: true
