services:
  wishlist:
    image: ghcr.io/cmintey/wishlist:latest
    container_name: wishlist
    restart: unless-stopped
    ports:
      - 3280:3280
    volumes:
      - ${DOCKER_APP_BASE_PATH}/wishlist/images:/usr/src/app/uploads  # This is where user image uploads will be stored
      - ${DOCKER_APP_BASE_PATH}/wishlist:/usr/src/app/data        # This is where the sqlite database will be stored
    environment:
      # ORIGIN: https://wishlist.example.com
      ORIGIN: http://wishlist.p3av3y.com # The URL your users will be connecting to
      TOKEN_TIME: 72 # hours until signup and password reset tokens expire
    labels:
      - com.centurylinklabs.watchtower.enable=true      