# See Portainer Community Edition Installation for more details: https://docs.portainer.io/start/install-ce/server/docker/linux
# docker compose --env-file=/mnt/nebula/docker/env-files/common.env up -d

services:
  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: "portainer"
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    environment:
      # Specify any environment variables that you want to be available to all stacks here
      - DOCKER_APP_BASE_PATH=${DOCKER_APP_BASE_PATH}
      - DOCKER_BASE_PATH=${DOCKER_BASE_PATH}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$DOCKER_BASE_PATH/env-files:/env-files:ro"
      - "$DOCKER_APP_BASE_PATH/portainer:/data"
