# obsidian

services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    networks:
      - pvnet
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - GUID=${PGID}
    volumes:
      - ${DOCKER_APP_BASE_PATH}/obsidian:/config
    ports:
      - 3200:3000
      - 3201:3001
    shm_size: "1gb"

networks:
   pvnet:
     external: true   