# Chromium

services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    restart: unless-stopped
    networks:
      - pvnet    
    #security_opt:
    #  - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - GUID=${PGID}
      - TZ=${TZ}
      #- CHROME_CLI=https://homepage.peav.us/
    volumes:
      - ${DOCKER_APP_BASE_PATH}/chromium:/config
    ports:
      - 3100:3000
      - 3101:3001
    shm_size: "1gb"
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
   pvnet:
     external: true      