# Syncthing

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    networks:
      - pvnet
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKER_APP_BASE_PATH}/syncthing:/config
      - ${NAS_NEBULA_BASE_PATH}:/nebula
      - ${NAS_GALAXY_BASE_PATH}:/galaxy
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
   pvnet:
     external: true   
