# arr

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    ports:
      - "8080:8080"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - GUID=${PGID}
      - NAS_GALAXY_BASE_PATH=${NAS_GALAXY_BASE_PATH}
      - DOCKER_APP_BASE_PATH=${DOCKER_APP_BASE_PATH}
    restart: unless-stopped
    volumes:
      - ${DOCKER_APP_BASE_PATH}/sabnzbd:/config
      - ${NAS_GALAXY_BASE_PATH}/media/downloads/sabnzbd:/downloads
      - ${NAS_GALAXY_BASE_PATH}/media/downloads/sabnzbd/incomplete:/incomplete-downloads
    labels:
      - com.centurylinklabs.watchtower.enable=true
