version: '3.6'

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    ports:
      - "8080:8080"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - GUID=${PGID}
    restart: unless-stopped
    volumes:
      - ${DOCKER_APP_BASE_PATH}/sabnzbd:/config
      - ${NAS_GALAXY_BASE_PATH}/media/downloads/sabnzbd:/downloads
      - ${NAS_GALAXY_BASE_PATH}/media/downloads/sabnzbd/incomplete:/incomplete-downloads
    labels:
      - com.centurylinklabs.watchtower.enable=true
      
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - GUID=${PGID}
    restart: unless-stopped
    volumes:
      - ${DOCKER_APP_BASE_PATH}/radarr:/config
      - ${NAS_GALAXY_BASE_PATH}/media/movies:/movies
      - ${NAS_GALAXY_BASE_PATH}/media/downloads/sabnzbd:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=true

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - GUID=${PGID}
    volumes:
      - ${DOCKER_APP_BASE_PATH}/readarr:/config
      - ${NAS_GALAXY_BASE_PATH}/media/books:/books
      - ${NAS_GALAXY_BASE_PATH}/media/downloads/sabnzbd:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped  
    labels:
      - com.centurylinklabs.watchtower.enable=true

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - GUID=${PGID}
    restart: unless-stopped
    volumes:
      - ${DOCKER_APP_BASE_PATH}/sonarr:/config
      - ${NAS_GALAXY_BASE_PATH}/media/tv:/tv
      - ${NAS_GALAXY_BASE_PATH}/media/downloads/sabnzbd:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=true
      
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    ports:
      - 8686:8686
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - GUID=${PGID}
    volumes:
      - ${DOCKER_APP_BASE_PATH}/lidarr:/config
      - ${NAS_GALAXY_BASE_PATH}/media/music:/music
      - ${NAS_GALAXY_BASE_PATH}/media/downloads/sabnzbd:/downloads
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
      
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    ports:
      - "5076:5076"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - GUID=${PGID}
    restart: unless-stopped
    volumes:
      - ${DOCKER_APP_BASE_PATH}/nzbhydra2:/config
      - ${NAS_GALAXY_BASE_PATH}/media/downloads/sabnzbd:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=true  

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - GUID=${PGID}
    volumes:
      - ${DOCKER_APP_BASE_PATH}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true     
