# 
#
# docker network create --driver macvlan --subnet 192.168.0.0/22 --ip-range 192.168.0.80/32 --macvlan-mode bridge -o parent=br0 reverse-proxy

# sudo docker network create -d macvlan --subnet 192.168.0.0/22 --gateway 192.168.0.1 --ip-range 192.168.0.80/32 -o parent=br0 reverse-proxy

# docker network create -d ipvlan --subnet 192.168.0.0/22 --gateway 192.168.0.1 --ip-range 192.168.0.80/32 -o ipvlan_mode=l2 -o parent=br0 reverse-proxy

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    # Attach to both networks
    networks:
      pvpub:
        ipv4_address: 192.168.0.80  # Its own public IP
        priority: 1000  # Higher number = Higher priority
      pvnet: {}                     # Internal bridge to talk to other apps
        priority: 10    # Lower priority        
    env_file: 
      - /env-files/nginx-proxy-manager.env
    environment:
      - DB_SQLITE_FILE=/data/npm.sqlite
      #- PUID=${PUID}
      #- PGID=${PUID}
      - TZ=${TZ}
    # Ports are technically redundant with macvlan but kept for reference
    # When you use a macvlan network, the container gets its own virtual network card with its own IP. You don't need to "map" the ports to the host anymore.
    #ports:  
    #  - 80:80
    #  - 443:443
    #  - 81:81
    volumes:
      # SSD: Fast database access and certificate storage
      - ${DOCKER_APP_BASE_PATH}/nginx-proxy-manager:/data
      - ${DOCKER_APP_BASE_PATH}/nginx-proxy-manager/certificates:/etc/letsencrypt
    cap_add:
      - NET_ADMIN
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  pvpub:
    external: true
  #pvnet:
  #  external: true
